spring:
 config:
  activate:
   on-profile: "qa"

build:
 version: "1.0"

accounts:
 message: "Welcome to the Banking Service FROM  QA SERVICE from LOANS MS"
 contactDetails:
  name: "User1"
  email: "user1@gmail.com"
 
 OnCallSupport:
  - 43543635
  - 433242352