services:
  accounts:
   image: "mohdrafiq2000/accounts:s4"
   container_name: Account-MicroService
   ports:
    - "8080:8080"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - BankingService


  loans:
   image: "mohdrafiq/loans:s4"
   container_name: "Loans-MicroService"
   ports:
    - "8090:8090"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - BankingService
   
  cards:
   image: "mohdrafiq/cards:s4"
   container_name: Cards-MicroService
   ports:
    - "9000:9000"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - BankingService

networks:
  BankingService:
   driver: "bridge"